"""Leakage-safe CPU model for ranking next-session long-only candidates.

The implementation resets all lagged features at session boundaries, predicts
cross-sectional excess returns, uses purged walk-forward validation, and blends
a linear model with a nonlinear CPU model. It produces research weights only.
"""
from __future__ import annotations

from dataclasses import dataclass
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from .optimize import forecast_mean_variance_weights

NEW_YORK = ZoneInfo("America/New_York")
INTERVAL_MINUTES = {"1m": 1, "15m": 15}
MIN_COVARIANCE_SCENARIOS = 5
FEATURE_COLUMNS = (
    "return_1", "return_2", "return_4", "return_8", "return_13", "return_26",
    "volatility_4", "volatility_13", "volatility_26", "volatility_ratio",
    "market_return_1", "market_return_4", "market_volatility_13",
    "relative_strength_1", "relative_strength_4", "relative_strength_13",
    "rank_return_1", "rank_return_4", "rank_return_13",
    "minute_sin", "minute_cos",
)


@dataclass(frozen=True)
class ForwardModelResult:
    validation: pd.DataFrame
    portfolio: pd.DataFrame
    status: dict[str, object]


def _regular_session_bars(bars: pd.DataFrame) -> pd.DataFrame:
    required = {"timestamp", "symbol", "close"}
    if missing := required.difference(bars.columns):
        raise ValueError(f"intraday bars are missing required columns: {sorted(missing)}")
    frame = bars.loc[:, ["timestamp", "symbol", "close"]].copy()
    frame["timestamp"] = pd.to_datetime(frame["timestamp"], utc=True, errors="coerce")
    frame["symbol"] = frame["symbol"].astype(str).str.upper().str.strip()
    frame["close"] = pd.to_numeric(frame["close"], errors="coerce")
    frame = frame.dropna(subset=["timestamp", "close"])
    frame = frame[(frame["close"] > 0) & frame["symbol"].ne("")]
    frame = frame.drop_duplicates(["symbol", "timestamp"], keep="last")
    local = frame["timestamp"].dt.tz_convert(NEW_YORK)
    minutes = local.dt.hour * 60 + local.dt.minute
    frame = frame[(minutes >= 570) & (minutes <= 960)].copy()
    local = frame["timestamp"].dt.tz_convert(NEW_YORK)
    frame["session_date"] = local.dt.tz_localize(None).dt.normalize()
    frame["minute_of_session"] = local.dt.hour * 60 + local.dt.minute - 570
    if frame.empty:
        raise ValueError("no positive bars fall in the US regular session")
    return frame.sort_values(["symbol", "session_date", "timestamp"]).reset_index(drop=True)


def _feature_frame(bars: pd.DataFrame) -> pd.DataFrame:
    frame = _regular_session_bars(bars)
    frame["log_close"] = np.log(frame["close"])
    session_group = frame.groupby(["symbol", "session_date"], sort=False)
    for lag in (1, 2, 4, 8, 13, 26):
        frame[f"return_{lag}"] = session_group["log_close"].diff(lag)
    for window in (4, 13, 26):
        frame[f"volatility_{window}"] = session_group["return_1"].transform(
            lambda values, w=window: values.rolling(w, min_periods=w).std()
        )
    frame["volatility_ratio"] = frame["volatility_4"] / frame["volatility_26"].replace(0, np.nan)

    for lag in (1, 4):
        frame[f"market_return_{lag}"] = frame.groupby("timestamp")[f"return_{lag}"].transform("median")
    frame["market_volatility_13"] = frame.groupby("timestamp")["volatility_13"].transform("median")
    for lag in (1, 4, 13):
        frame[f"relative_strength_{lag}"] = frame[f"return_{lag}"] - frame.groupby("timestamp")[f"return_{lag}"].transform("median")
        frame[f"rank_return_{lag}"] = frame.groupby("timestamp")[f"return_{lag}"].rank(pct=True) - 0.5

    angle = 2.0 * np.pi * frame["minute_of_session"] / 390.0
    frame["minute_sin"] = np.sin(angle)
    frame["minute_cos"] = np.cos(angle)
    return frame.replace([np.inf, -np.inf], np.nan)


def build_forward_dataset(bars: pd.DataFrame, *, interval: str, horizon_minutes: int = 500) -> tuple[pd.DataFrame, int, int]:
    if interval not in INTERVAL_MINUTES:
        raise ValueError(f"unsupported interval {interval!r}")
    if horizon_minutes < 1:
        raise ValueError("horizon_minutes must be positive")
    bar_minutes = INTERVAL_MINUTES[interval]
    horizon_bars = int(np.ceil(horizon_minutes / bar_minutes))
    effective_minutes = horizon_bars * bar_minutes
    frame = _feature_frame(bars)

    # Targets may span sessions, but the exact endpoint is generated by the full
    # symbol history. Features themselves never cross a session boundary.
    symbol_group = frame.groupby("symbol", sort=False)
    frame["future_close"] = symbol_group["close"].shift(-horizon_bars)
    frame["target_timestamp"] = symbol_group["timestamp"].shift(-horizon_bars)
    frame["forward_log_return"] = np.log(frame["future_close"] / frame["close"])
    frame["target_excess_return"] = frame["forward_log_return"] - frame.groupby("timestamp")["forward_log_return"].transform("median")
    dataset = frame.dropna(subset=[*FEATURE_COLUMNS, "target_excess_return", "target_timestamp"]).copy()
    dataset = dataset[dataset["target_timestamp"] > dataset["timestamp"]]
    return dataset, horizon_bars, effective_minutes


def _fit_predict(train: pd.DataFrame, test: pd.DataFrame) -> np.ndarray:
    linear = make_pipeline(StandardScaler(), Ridge(alpha=10.0))
    nonlinear = HistGradientBoostingRegressor(
        learning_rate=0.05, max_iter=150, max_leaf_nodes=15,
        l2_regularization=1.0, min_samples_leaf=40, random_state=42,
    )
    x_train = train.loc[:, FEATURE_COLUMNS]
    y_train = train["target_excess_return"]
    linear.fit(x_train, y_train)
    nonlinear.fit(x_train, y_train)
    return 0.5 * linear.predict(test.loc[:, FEATURE_COLUMNS]) + 0.5 * nonlinear.predict(test.loc[:, FEATURE_COLUMNS])


def _purged_walk_forward(dataset: pd.DataFrame, *, validation_blocks: int = 5) -> pd.DataFrame:
    timestamps = pd.DatetimeIndex(sorted(dataset["timestamp"].unique()))
    columns = ["fold", "train_rows", "test_rows", "test_start", "test_end", "mse", "spearman_ic", "directional_accuracy", "top_bottom_spread"]
    if len(timestamps) < validation_blocks * 10:
        return pd.DataFrame(columns=columns)
    starts = np.linspace(int(len(timestamps) * 0.50), len(timestamps), validation_blocks + 1, dtype=int)
    rows: list[dict[str, object]] = []
    for fold, (start, end) in enumerate(zip(starts[:-1], starts[1:]), 1):
        if start >= len(timestamps):
            continue
        test_start = timestamps[start]
        test_end = timestamps[min(end, len(timestamps) - 1)] + pd.Timedelta(nanoseconds=1)
        train = dataset[dataset["target_timestamp"] < test_start]
        test = dataset[(dataset["timestamp"] >= test_start) & (dataset["timestamp"] < test_end)]
        if len(train) < 500 or len(test) < 100:
            continue
        prediction = _fit_predict(train, test)
        actual = test["target_excess_return"].to_numpy()
        ic = spearmanr(prediction, actual).statistic
        ranked = pd.DataFrame({"prediction": prediction, "actual": actual})
        cutoff = max(1, len(ranked) // 10)
        top_bottom = ranked.nlargest(cutoff, "prediction")["actual"].mean() - ranked.nsmallest(cutoff, "prediction")["actual"].mean()
        rows.append({
            "fold": fold, "train_rows": len(train), "test_rows": len(test),
            "test_start": test_start, "test_end": test_end,
            "mse": float(np.mean((prediction - actual) ** 2)),
            "spearman_ic": float(ic) if np.isfinite(ic) else np.nan,
            "directional_accuracy": float(np.mean(np.sign(prediction) == np.sign(actual))),
            "top_bottom_spread": float(top_bottom),
        })
    return pd.DataFrame(rows, columns=columns)


def _select_covariance_scenarios(
    history: pd.DataFrame,
    prediction: pd.Series,
    *,
    top_n: int,
    max_weight: float,
) -> tuple[pd.DataFrame, pd.Index]:
    """Keep the highest-ranked cohort with enough shared observed outcomes.

    IEX bars are legitimately sparse for some constituents.  Covariance is
    therefore estimated only from observed, same-session forward returns; the
    function never fills missing returns merely to make an optimizer run.
    """
    if top_n < 2:
        raise ValueError("top_n must be at least two")
    if max_weight <= 0:
        raise ValueError("max_weight must be positive")
    if max_weight * top_n < 1 - 1e-12:
        raise ValueError("top_n and max_weight cannot form a fully invested portfolio")

    ranked = prediction.dropna().sort_values(ascending=False)
    panel = history.pivot_table(
        index="session_date",
        columns="symbol",
        values="target_excess_return",
        aggfunc="last",
    ).sort_index()
    available_symbols = ranked.index.intersection(panel.columns, sort=False)
    ranked = ranked.reindex(available_symbols)
    panel = panel.reindex(columns=ranked.index)
    availability = panel.notna().to_numpy()
    minimum_assets = max(2, int(np.ceil((1 - 1e-12) / max_weight)))

    best_symbols: list[str] = []
    best_mask: np.ndarray | None = None
    best_score: tuple[int, float] = (0, float("-inf"))
    for seed_index in range(len(ranked)):
        shared = availability[:, seed_index].copy()
        if int(shared.sum()) < MIN_COVARIANCE_SCENARIOS:
            continue
        selected_indices = [seed_index]
        candidate_order = [seed_index, *range(seed_index), *range(seed_index + 1, len(ranked))]
        for candidate_index in candidate_order[1:]:
            expanded = shared & availability[:, candidate_index]
            if int(expanded.sum()) >= MIN_COVARIANCE_SCENARIOS:
                selected_indices.append(candidate_index)
                shared = expanded
                if len(selected_indices) == top_n:
                    break
        score = (len(selected_indices), float(ranked.iloc[selected_indices].sum()))
        if score > best_score:
            best_score = score
            best_symbols = ranked.index[selected_indices].tolist()
            best_mask = shared

    if len(best_symbols) < minimum_assets or best_mask is None:
        return pd.DataFrame(), pd.Index([], dtype="object")
    scenarios = panel.loc[best_mask, best_symbols].dropna(axis=0, how="any")
    return scenarios, pd.Index(best_symbols)


def run_forward_research(bars: pd.DataFrame, *, interval: str, horizon_minutes: int = 500, top_n: int = 20, max_weight: float = 0.10, min_sessions: int = 20) -> ForwardModelResult:
    dataset, horizon_bars, effective_minutes = build_forward_dataset(bars, interval=interval, horizon_minutes=horizon_minutes)
    validation = _purged_walk_forward(dataset)
    session_count = int(dataset["session_date"].nunique())
    status: dict[str, object] = {
        "model_run": False, "model_version": "leakage_safe_ensemble_v2",
        "requested_horizon_minutes": horizon_minutes, "effective_horizon_minutes": effective_minutes,
        "interval": interval, "horizon_bars": horizon_bars,
        "sessions_with_features": session_count, "minimum_sessions": min_sessions,
        "validation_folds": int(len(validation)),
        "mean_spearman_ic": float(validation["spearman_ic"].mean()) if not validation.empty else None,
        "mean_directional_accuracy": float(validation["directional_accuracy"].mean()) if not validation.empty else None,
        "mean_top_bottom_spread": float(validation["top_bottom_spread"].mean()) if not validation.empty else None,
    }
    if session_count < min_sessions or len(validation) < 2:
        status["reason"] = "insufficient complete regular-session history for purged validation"
        return ForwardModelResult(validation, pd.DataFrame(columns=["symbol", "target_weight"]), status)

    features = _feature_frame(bars)
    latest_timestamp = features["timestamp"].max()
    current = features[features["timestamp"] == latest_timestamp].dropna(subset=FEATURE_COLUMNS).copy()
    history = dataset[dataset["target_timestamp"] < latest_timestamp]
    if len(current) < 2 or len(history) < 500:
        status["reason"] = "insufficient current features or completed labels"
        return ForwardModelResult(validation, pd.DataFrame(columns=["symbol", "target_weight"]), status)
    prediction = pd.Series(_fit_predict(history, current), index=current["symbol"], name="predicted_forward_excess_return")
    scenarios, selected_symbols = _select_covariance_scenarios(
        history,
        prediction,
        top_n=top_n,
        max_weight=max_weight,
    )
    if scenarios.empty:
        status["reason"] = "insufficient complete forward-return scenarios for a capped covariance portfolio"
        return ForwardModelResult(validation, pd.DataFrame(columns=["symbol", "target_weight"]), status)
    selected = prediction.reindex(selected_symbols)
    allocation = forecast_mean_variance_weights(scenarios, selected, risk_aversion=10.0, max_weight=max_weight)
    portfolio = pd.DataFrame({"symbol": allocation.weights.index, "target_weight": allocation.weights.values})
    portfolio["predicted_forward_excess_return"] = portfolio["symbol"].map(prediction)
    portfolio = portfolio.sort_values("target_weight", ascending=False).reset_index(drop=True)
    status.update({
        "model_run": True, "reason": "research_only", "optimizer_status": allocation.status,
        "portfolio_predicted_forward_excess_return": allocation.expected_return,
        "forward_return_scenarios": int(len(scenarios)),
        "covariance_assets": int(len(selected_symbols)),
        "latest_feature_timestamp": latest_timestamp.isoformat(),
    })
    return ForwardModelResult(validation, portfolio, status)
